name: Deploy to server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: 167.99.242.135
        USER: root
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
         ssh -i private_key   -o StrictHostKeyChecking=no  $USER@$HOST  "
          cd /root/jawib-backend/  && git pull  &&
          docker  buildx build -t    jawib-backend . &&
          docker rm -f jawib-backend
          docker run -d -p 3000:80 --name=jawib-backend --restart=unless-stopped  jawib-backend "

